name: MinGW

on:
  workflow_dispatch:  # This event triggers the workflow manually.
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up minGW
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          version: latest

      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Configure CMake Debug
        run: cmake -B ${{github.workspace}}/build_debug -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=OFF
      - name: Build
        run: cmake --build ${{github.workspace}}/build_debug --config Debug
      - name: Test
        working-directory: ${{github.workspace}}/build_debug/tests
        run: ./unit-tests